### ISSUE TITLE
17.1 Build

### ISSUE THREAD

**Issue by ghost** [DevelopedInside/android_device_wileyfox_marmite#13]
"DevelopedInside/android_device_wileyfox_marmite" path="device/wileyfox/marmite" remote="github" revision="staging/los-17.1-repart-rebase"
"DevelopedInside/proprietary_vendor_wileyfox" path="vendor/wileyfox" remote="github" revision="staging/los-17.1-rebase"   "DevelopedInside/android_kernel_wileyfox_msm8937" path="kernel/wileyfox/msm8937" remote="github" revision="lineage-17"

Used the above  in a local repo to build a 17.1 crDroid rom.
1 the boot.img appears corrupt as it causes a boot loop replacing this fixes this.
2 there are no indicator lights.
3 17.1 complains about the SELinux being disabled.

I should have mentioned that this was for the wileyfox marmite phone.

I have just built a lineage rom which also has the above errors.

**Comment by nikith290** [comment]
Hi!

First of all, lineage-17.1 trees is still in **STAGING** .
So if you build something, you **MUST** be ready to troubleshooting.

_1 the boot.img appears corrupt as it causes a boot loop replacing this fixes this._
Cant reproduce. All works fine on my builds. Give logs and maybe we can help.

_2 there are no indicator lights._
We know

_3 17.1 complains about the SELinux being disabled._
Not necessary

_I have just built a lineage rom which also has the above errors._
Cauze you using same device tree? :)

_build a 17.1 crDroid rom_
Also, im already build it and you can download it from https://crdroid.net/marmite

**Comment by ghost** [comment]
It is the DevelopedInside boot.img at 14.9Mb that is corrupt? yours at 29.5Mb  works.
How can I download your new 6.8 rom  09/07/2020 its not on sourceforge?

**Comment by nikith290** [comment]
_It is the DevelopedInside boot.img at 14.9Mb that is corrupt? yours at 29.5Mb works._
We dont shipping prebuild boot.img. And i'm saying again. LOGS or i cant help you.

_How can I download your new 6.8 rom 09/07/2020 its not on sourceforge?_
What? I didnt build it on 09/07.
It will build it tumorrow.

**Comment by ghost** [comment]
I use your boot.img from your 04/06/2020 rom and this works and so do not need help for this.
This is not the same as the one on the this web site so perhaps needs to be uploaded?
Thanks for the new Rom.

**Comment by robin0800** [comment]
The changes to the Kernel are most welcome there are a few that mention LED's is this meant to fix the led not working?
The updated boot.img still bootloops no idea why? nikith290 rom, boot.img still works.
