### ISSUE TITLE
Build System staging/lineage-17.1 broken

### ISSUE THREAD

**Issue by ghost** [DevelopedInside/android_device_wileyfox_marmite#14]
The Build System is missing two files it claims **e2fsdrioid** and **selinux_xattr** were these removed by mistake? or is the build system wrong?
This may not be the only error as other things appear to fail before it complains about the missing files.
This is right at the end of the build process when it is making the zips etc.

will attach terminal output tomorrow !

[Staging Lineage 17.1 Build.txt]
(https://github.com/DevelopedInside/android_device_wileyfox_marmite/files/4973470/Staging.Lineage.17.1.Build.txt)

Just built a rom using
kernel staging/lineage-17.1
vendor staging/lineage-17.1
device staging/los-17.1-repart-rebase
and it built successfully. 
All the above errors must be in device staging/lineage-17.1
Had to also change vendor to staging/los-17.1-rebase
before the Rom would boot.

**Comment by uixdess** [comment]
**Hello!**

Why do you open issues every time? I am repeating again the tree is in staging, so let's read definition what is it staging. `staging - classify as having reached a particular stage in the expected progression`.

So, it shouldn't work as it is. We just reached something. Also, if you will be smarter, you will get easy solution on GitHub and also see that the [sepolicy is committed](https://github.com/DevelopedInside/android_device_wileyfox_marmite/blob/staging/lineage-17.1/BoardConfig.mk#L259) 

Do not be stupid buildbot ☺️

Try to learn something before opening obtuse issue. No one will help you throughout life.

**Have a nice day!**

**P.S.** I hope you will be more attentive and smarter.

**Comment by ghost** [comment]
Many Thanks, I can close this now!
