### ISSUE TITLE
Fingerprint problem

### ISSUE THREAD

**Issue by ghost** [DevelopedInside/android_device_wileyfox_marmite#18]
Thank you for supporting Wileyfox and keeping it alive. I installed LOS 17 and enjoy using it except for one problem: fingerprint scanner doesn't work. There's an option in the menu, but the scanner doesn't react to the touch. I attached the log if you can find the time to look into it and suggest what to do with it. 
https://paste.nomagic.uk/?9b40ef80e8a1caf8#8P3KTywk1M2Nw7hVEVe4uJT2uJJ9GPiZ3dUMFGVASMC9

**Comment by uixdess** [comment]
Already fixed.
