### ISSUE TITLE
Bluetooth Problem

### ISSUE THREAD

**Issue by robin0800** [DevelopedInside/android_device_wileyfox_marmite#19]
I used the two 18.1 branches and the staging 18.0 branch to make a Lineageos Rom.
Rom builds, installs and runs.
There is bluetooth problem in that it toggles switch on and switch off  and therefore is unusable.

**Comment by uixdess** [comment]
Hello, @robin0800 !

I know about troubles. I just upreved device to LineageOS 18.1. 

If you know the solution feel free to PR.

Good day.

**Comment by robin0800** [comment]
The 18.1 Branch says ....
 This branch is 105 commits ahead of lineage-17.1.
Take your pick?

**Comment by uixdess** [comment]
It means that in comparison with lineage-17.1 branch there are more 105 commits

**Comment by robin0800** [comment]
So there is only one Bluetooth change?

**Comment by uixdess** [comment]
No.

That commits for bringing up to 11 Android

**Comment by robin0800** [comment]
11 is 18.1 So not sure what you mean?

**Comment by uixdess** [comment]
LineageOS 18.1 is based on android 11 (R).

**Comment by robin0800** [comment]
This is fixed since January 2022 update.
