### ISSUE TITLE
Bootloader versions

### ISSUE THREAD

**Issue by TippyLion28** [DevelopedInside/android_device_wileyfox_marmite#2]
Dirty flashing the latest build over the last one gave me an error 7 and the following log message:
script aborted: This package supports bootloader(s): marmite-N-g471c27e, marmite-N-g5531d45; this device has bootloader marmite-N-g2b20015.
This package supports bootloader(s): marmite-N-g471c27e, marmite-N-g5531d45; this device has bootloader marmite-N-g2b20015.
Updater process ended with ERROR: 7
Could this bootloader version be added to the asserts list or do I need to update my bootloader somehow?

**Comment by BeYkeRYkt** [comment]
from which version are you updated?

_Отправлено с моего OnePlus One с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by REDGuineaPig** [comment]
I'm Upgrading from the last build in the thread

https://forum.xda-developers.com/showthread.php?p=74246297#post74246297

On 23 Nov 2017 3:57 am, "Vladimir Mikhaylov" <notifications@github.com>
wrote:

Which version are you upgrading from?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DevelopedInside/android_device_wileyfox_marmite/issues/2#issuecomment-346527446>,
or mute the thread

**Comment by TippyLion28** [comment]
I'm Upgrading from the last build in the thread

https://forum.xda-developers.com/showthread.php?p=74246297#post74246297

**Comment by BeYkeRYkt** [comment]
@REDGuineaPig
Flash radio files from the official TOS249H fastboot rom and try flash LineageOS again.

_Отправлено с моего OnePlus One с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by TippyLion28** [comment]
Do I just flash the boot.img? Will that affect my Magisk?
EDIT: I'm lost, how do I flash the radio files?

**Comment by BeYkeRYkt** [comment]
@REDGuineaPig 
Flash this files from fastboot:
```
fastboot flash modem NON-HLOS.bin
fastboot flash dsp adspso.bin
fastboot flash devcfg devcfg.mbn
fastboot flash aboot emmc_appsboot.mbn
fastboot flash keymaster keymaster.mbn
fastboot flash rpm rpm.mbn
fastboot flash sbl1 sbl1.mbn
fastboot flash splash splash.img
fastboot flash tz tz.mbn
```

**Comment by TippyLion28** [comment]
I flashed modem, dsp and devcfg but trying to flash rpm, aboot, sbl1 and tz gives me this:
FAILED (remote: Critical partition flashing is not allowed)
Do I just continue or will it brick my phone?

**Comment by BeYkeRYkt** [comment]
@REDGuineaPig 

> fastboot flashing unlock_critical 

and flash again

**Comment by TippyLion28** [comment]
So it will erase my data first?

**Comment by BeYkeRYkt** [comment]
@REDGuineaPig 
It seems not. But make a backup copy just in case.

**Comment by TippyLion28** [comment]
It did, but everything is working now and I have an up to date bootloader. Thanks for the help and your work on this rom :)
