### ISSUE TITLE
No VoLTE/VoWiFi options even if magisk voenabler module installed

### ISSUE THREAD

**Issue by SlyFoxeh** [DevelopedInside/android_device_wileyfox_marmite#20]
VoLTE/VoWiFi options doesnt show, even if magisk voenabler module installed, same if manually modded build.rpop 
# Debug Options
persist.dbg.ims_volte_enable=1
persist.dbg.volte_avail_ovr=1
persist.dbg.vt_avail_ovr=1
persist.dbg.wfc_avail_ovr=1

# Data Options
# Commented this line out as it was reported to break WiFi calling on some carriers. Not even sure if it's required to begin with.
persist.data.iwlan.enable=true
persist.data.iwlan=1
persist.data.iwlan.ipsec.ap=1

# Radio Options
persist.radio.volte.dan_support=true
persist.radio.rat_on=combine
persist.radio.data_ltd_sys_ind=1
persist.radio.data_con_rprt=1
persist.radio.calls.on.ims=1
persist.radio.VT_ENABLE=1

# Other Options
persist.sys.cust.lte_config=true
persist.rcs.supported=1

Empty folder with modem configs in /vendor/rfs/msm/mpss/readonly/vendor/mbn/mcfg_sw

In attached file full stock mbn configs from a pixel 3a and should work on  Wileyfox Swift 2

[VOLTE12_pixel3a.zip](https://github.com/DevelopedInside/android_device_wileyfox_marmite/files/6759440/VOLTE12_pixel3a.zip)

**Comment by dereference23** [comment]
Hello!
Our modem firmware doesn't support VoLTE and there is no way to add it.
