### ISSUE TITLE
teamwin twrp error code 7

### ISSUE THREAD

**Issue by neotje** [DevelopedInside/android_device_wileyfox_marmite#4]
I haven't updated my phone in a while, but when I update I get error code 7. the latest update that I installed was "lineage-14.1-20171031_032753-UNOFFICIAL-marmite.zip".

**Comment by BeYkeRYkt** [comment]
https://github.com/DevelopedInside/android_device_wileyfox_marmite/issues/2 , but need flash TOS319I

**Comment by neotje** [comment]
`fastboot flashing unlock_critical`
this command does not work for me. when I use this command I get this error:
`...
FAILED (remote: oem unlock is not allowed)
finished. total time: 0.003s`

**Comment by vm03** [comment]
Ask it on xda 
https://forum.xda-developers.com/swift-2/help/help-thread-questions-t3527631
